# Generated by Django 6.1.1 on 2026-09-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codigo_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
